FROM alpine:latest as packager

RUN mkdir /info
RUN date >/info/build_date.txt

RUN apk --no-cache add openjdk11-jdk openjdk11-jmods

RUN apk --no-cache add nano

RUN apk --no-cache add ffmpeg


ENV PROPERTIES_PATH src/main/resources/application.properties
COPY build/libs/springmvcdemo-1.0.1.jar /var/app.jar
COPY $PROPERTIES_PATH /cfg/application.properties

copy etc/*.* /etc/

EXPOSE 9999

ENTRYPOINT java -jar /var/app.jar --spring.config.location=/cfg/application.properties




